Adds `TYPICAL_ERRORS' array and adds back safe navigation operator `&.` to `results = response&.`: - Prevents:  'NameError:        uninitialized constant ArticleImporter::TYPICAL_ERRORS' when `ApiErrorHandling` sets the error level - Prevents: 'NoMethodError:        undefined method `dig' for nil:NilClass              results = response.dig('query', 'pages')                                ^^^^' when response is nil ( for example when methods that call `import_articles_by_title` are mocked, the api_post response becomes `nil`)